<a href="https://colab.research.google.com/github/am-robin17/SaM-Lab-Assignments/blob/main/Simulation_Lab_Assignment_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sympy import Matrix
import matplotlib.pyplot as plt
import seaborn as sns


In [3]:
# With Seed
np.random.seed(10)  # Setting seed to 10
seeded_matrix = np.random.randint(1, 51, (3, 3))
print("Seeded Random Matrix:\n", seeded_matrix)

Seeded Random Matrix:
 [[10 37 16]
 [ 1 50 29]
 [26 30 49]]


In [5]:
# Without Seed
np.random.seed(None)  # No seed, generates different values each time
non_seeded_matrix = np.random.randint(1, 51, (3, 3))
print("\nNon-Seeded Random Matrix:\n", non_seeded_matrix)


Non-Seeded Random Matrix:
 [[19 14 18]
 [50 24 36]
 [44 27  1]]


In [6]:
# Observation and Explanation

# With Seed - When I executed the codes multiple times in Colab Notebook, it showed the same output each and every time. This is because we've set a seed and it allowed the code to retain the same output.

# Without Seed - However, when executed the code without seed, the output changed each time I executed the code.

# What "Seed" does here - A seed is an initial value provided to a pseudo-random number generator. It sets the starting point for the sequence of random numbers. In machine learning and simulations, fixing the seed ensures that results are consistent and comparable across multiple runs.